### ISSUE TITLE
Creating Routes

### ISSUE THREAD

**Issue by AgostonSzepessy** [movnet-capstone/backend#6]
This is issue will keep track of the routes and who's assigned to do them.

- [x] User
- [x] Theater
- [x] Movie
- [x] Showtime
- [x] Friend
- [x] Event
- [x] Chat
- [x] Message

**Comment by sshrest9** [comment]
i'll do theater and showtime

**Comment by AgostonSzepessy** [comment]
I'm doing User, Friend, Chat, and Message

**Comment by Stuart-Wilcox** [comment]
I'm doing Movie, Theater, Showtime, and Event

**Comment by AgostonSzepessy** [comment]
Narrowed down remaining routes in #12
